
package projectdb_2022_23;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;

public class adminFrame extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String password = "123456";
    private static final String dataB = "jdbc:mysql://localhost:3306/travel_agency";
    
    Connection sqlConn = null;
    PreparedStatement ps = null;
    
    String adadminAT = null;
    String adtype = null;
    String addiploma = null;
    String adname = null;
    String adlname = null;
    
    public adminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void updateAddDelAdmin(){
        try{
             adadminAT = adadminATtxt.getText();
             adtype = adtypetxt.getText();
             addiploma = addiplomatxt.getText();
             adname = adadminnametxt.getText();
             adlname = adadminlnametxt.getText();
 
             Class.forName("com.mysql.jdbc.Driver");
             sqlConn = DriverManager.getConnection(dataB,username,password);
        }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, e);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRESETbr = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnReturnbr = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        adadminATtxt = new javax.swing.JTextField();
        btnUPDATEbr = new javax.swing.JButton();
        btnADDbr = new javax.swing.JButton();
        btnResetbr = new javax.swing.JButton();
        btnDELETEbr = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        adtypetxt = new javax.swing.JTextField();
        addiplomatxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnViewAdm = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        adadminnametxt = new javax.swing.JTextField();
        adadminlnametxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRESETbr.setBackground(new java.awt.Color(0, 0, 0));
        btnRESETbr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 8));
        btnRESETbr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Admin Table");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 380, 70));

        btnReturnbr.setFont(new java.awt.Font("Segoe UI Semibold", 1, 26)); // NOI18N
        btnReturnbr.setText("Return");
        btnReturnbr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReturnbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnbrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnReturnbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 670, 130, 50));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "adm_AT", "adm_type", "adm_diploma"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnRESETbr.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 790, 230));

        adadminATtxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        adadminATtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adadminATtxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(adadminATtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 460, 30));

        btnUPDATEbr.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnUPDATEbr.setText("UPDATE");
        btnUPDATEbr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUPDATEbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEbrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnUPDATEbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, 130, 50));

        btnADDbr.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnADDbr.setText("ADD");
        btnADDbr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnADDbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDbrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnADDbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 160, 130, 50));

        btnResetbr.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnResetbr.setText("RESET");
        btnResetbr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetbrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnResetbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 370, 130, 50));

        btnDELETEbr.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnDELETEbr.setText("DELETE");
        btnDELETEbr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDELETEbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEbrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnDELETEbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 300, 130, 50));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("admin AT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 130, 30));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("type");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, -1));

        adtypetxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        adtypetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adtypetxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(adtypetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 460, 30));

        addiplomatxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        addiplomatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addiplomatxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(addiplomatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 460, 30));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("diploma");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 120, -1));

        btnViewAdm.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnViewAdm.setText("View Data");
        btnViewAdm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAdmActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnViewAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, 130, 40));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("admin Name");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 160, -1));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setText("admin Lastname");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 170, 30));

        adadminnametxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        adadminnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adadminnametxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(adadminnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 460, -1));

        adadminlnametxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        adadminlnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adadminlnametxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(adadminlnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 460, -1));

        getContentPane().add(btnRESETbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnbrActionPerformed
        // TODO add your handling code here:
        IT_operationsFrame s = new IT_operationsFrame();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturnbrActionPerformed

    private void adadminATtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adadminATtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adadminATtxtActionPerformed

    private void btnUPDATEbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEbrActionPerformed
        // TODO add your handling code here:

        try{
            updateAddDelAdmin();
            
            if(!(addiploma.isEmpty()) && adtype.isEmpty()){
                ps = sqlConn.prepareStatement("UPDATE admin set adm_diploma=? WHERE adm_AT=?");
                ps.setString(2, adadminAT);
                ps.setString(1, addiploma);
                ps.executeUpdate();
            }else if(addiploma.isEmpty() && !(adtype.isEmpty())){
                ps = sqlConn.prepareStatement("UPDATE admin set adm_type=? WHERE adm_AT=?");
                ps.setString(2, adadminAT);
                ps.setString(1, adtype);
                ps.executeUpdate();
            }else{
                ps = sqlConn.prepareStatement("UPDATE admin set adm_type=?,adm_diploma=? WHERE adm_AT=?");
                ps.setString(1,adtype);
                ps.setString(2, addiploma);
                ps.setString(3, adadminAT);
                ps.executeUpdate();
            }
            

            adadminATtxt.setText("");
            addiplomatxt.setText("");
            adtypetxt.setText("");
            JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
        }catch(Exception e){
            //java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnUPDATEbrActionPerformed

    private void btnADDbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDbrActionPerformed
        // TODO add your handling code here:

        try{
            updateAddDelAdmin();

            ps = sqlConn.prepareStatement("insert into admin(adm_AT,adm_type,adm_diploma)values(?,?,?)");

            ps.setString(1, adadminAT);
            ps.setString(2,adtype);
            ps.setString(3, addiploma);

            ps.executeUpdate();
            adadminATtxt.setText("");
            addiplomatxt.setText("");
            adtypetxt.setText("");
            JOptionPane.showMessageDialog(this, "Added Successfully!");
        }catch(Exception e){
            //java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnADDbrActionPerformed

    private void btnResetbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetbrActionPerformed
        // TODO add your handling code here:
        adadminATtxt.setText("");
        addiplomatxt.setText("");
        adtypetxt.setText("");
    }//GEN-LAST:event_btnResetbrActionPerformed

    private void btnDELETEbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEbrActionPerformed
        // TODO add your handling code here:
        try{
            updateAddDelAdmin();
            
            if(!(adname.isEmpty()) && !(adlname.isEmpty()) && addiploma.isEmpty() && adtype.isEmpty()){
                ps = sqlConn.prepareStatement("{call delete_admin(?,?)}");
                ps.setString(1, adname);
                ps.setString(2, adlname);
                int rowsAffected = ps.executeUpdate();
                if(rowsAffected == 1)
                    JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
                else
                    JOptionPane.showMessageDialog(this, "Record Not Deleted!");
            }else if(!(addiploma.isEmpty()) && adtype.isEmpty() && adname.isEmpty() && adlname.isEmpty()){
                ps = sqlConn.prepareStatement("DELETE FROM admin WHERE adm_AT=? AND (adm_diploma LIKE ?)");
                ps.setString(1, adadminAT);
                ps.setString(2, addiploma);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
            }else if(addiploma.isEmpty() && !(adtype.isEmpty()) && adname.isEmpty() && adlname.isEmpty()){
                ps = sqlConn.prepareStatement("DELETE FROM admin WHERE adm_AT=? AND (adm_type LIKE ?)");
                ps.setString(1, adadminAT);
                ps.setString(2, adtype);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
            }
        }catch(java.sql.SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnDELETEbrActionPerformed

    private void adtypetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adtypetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adtypetxtActionPerformed

    private void addiplomatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addiplomatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addiplomatxtActionPerformed

    private void btnViewAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAdmActionPerformed
        // TODO add your handling code here:
        try{

            sqlConn = DriverManager.getConnection(dataB,username,password);
            PreparedStatement pst = sqlConn.prepareStatement("SELECT * FROM admin");
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3)});
            }
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnViewAdmActionPerformed

    private void adadminnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adadminnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adadminnametxtActionPerformed

    private void adadminlnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adadminlnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adadminlnametxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adadminATtxt;
    private javax.swing.JTextField adadminlnametxt;
    private javax.swing.JTextField adadminnametxt;
    private javax.swing.JTextField addiplomatxt;
    private javax.swing.JTextField adtypetxt;
    private javax.swing.JButton btnADDbr;
    private javax.swing.JButton btnDELETEbr;
    private javax.swing.JPanel btnRESETbr;
    private javax.swing.JButton btnResetbr;
    private javax.swing.JButton btnReturnbr;
    private javax.swing.JButton btnUPDATEbr;
    private javax.swing.JButton btnViewAdm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
