
package projectdb_2022_23;

//import javax.swing.JFrame;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.CallableStatement;
import javax.swing.table.DefaultTableModel;

public class branchFrame extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String password = "123456";
    private static final String dataB = "jdbc:mysql://localhost:3306/travel_agency";
    
    Connection sqlConn = null;
    PreparedStatement ps = null;
    CallableStatement call = null;
    
    String brcode = null;
    String brstreet = null;
    String brnum = null;
    String brcity = null;
    String sql_string = "CALL branch_info(?)";
    
    ResultSet rs2; int rowCount = 0;
    
    public branchFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    public void updateAddDelBranch(){
        try{
             brcode = brcodetxt.getText();
             brstreet = brstreettxt.getText();
             brnum = brnumtxt.getText();
             brcity = brcitytxt.getText();
 
             Class.forName("com.mysql.jdbc.Driver");
             sqlConn = DriverManager.getConnection(dataB,username,password);
        }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, e);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnRESETbr = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnReturnbr = new javax.swing.JButton();
        brcodetxt = new javax.swing.JTextField();
        btnUPDATEbr = new javax.swing.JButton();
        btnADDbr = new javax.swing.JButton();
        btnResetbr = new javax.swing.JButton();
        btnDELETEbr = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        brstreettxt = new javax.swing.JTextField();
        brnumtxt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        brcitytxt = new javax.swing.JTextField();
        btnEMPLOYEEINFO = new javax.swing.JButton();
        btnBRANCHINFO = new javax.swing.JButton();
        btnBRANCHTABLE = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnClrTbls = new javax.swing.JButton();
        bntProfCos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRESETbr.setBackground(new java.awt.Color(0, 0, 0));
        btnRESETbr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 8));
        btnRESETbr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Branch Table");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 380, 70));

        btnReturnbr.setFont(new java.awt.Font("Segoe UI Semibold", 1, 26)); // NOI18N
        btnReturnbr.setText("Return");
        btnReturnbr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReturnbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnbrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnReturnbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 700, 130, 50));

        brcodetxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        brcodetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brcodetxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(brcodetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 460, 30));

        btnUPDATEbr.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnUPDATEbr.setText("UPDATE");
        btnUPDATEbr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUPDATEbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEbrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnUPDATEbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 180, 130, 50));

        btnADDbr.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnADDbr.setText("ADD");
        btnADDbr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnADDbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDbrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnADDbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 110, 130, 50));

        btnResetbr.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnResetbr.setText("RESET");
        btnResetbr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetbrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnResetbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 320, 130, 50));

        btnDELETEbr.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnDELETEbr.setText("DELETE");
        btnDELETEbr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDELETEbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEbrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnDELETEbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 250, 130, 50));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("branch code");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 260, 30));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("street");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        brstreettxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        brstreettxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brstreettxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(brstreettxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 460, 30));

        brnumtxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        brnumtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnumtxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(brnumtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 460, 30));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("city");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("number");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        brcitytxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        brcitytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brcitytxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(brcitytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 460, 30));

        btnEMPLOYEEINFO.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnEMPLOYEEINFO.setText("EMPLOYEE INFO");
        btnEMPLOYEEINFO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEMPLOYEEINFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEMPLOYEEINFOActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnEMPLOYEEINFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 540, 120, 30));

        btnBRANCHINFO.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBRANCHINFO.setText("BRANCH INFO");
        btnBRANCHINFO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBRANCHINFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBRANCHINFOActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnBRANCHINFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 480, 120, 40));

        btnBRANCHTABLE.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnBRANCHTABLE.setText("BRANCH TABLE");
        btnBRANCHTABLE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBRANCHTABLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBRANCHTABLEActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnBRANCHTABLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 400, 120, 40));

        jTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Lastname", "Salary", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setPreferredSize(new java.awt.Dimension(500, 80));
        jTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable.setShowGrid(false);
        jScrollPane2.setViewportView(jTable);

        btnRESETbr.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 810, 100));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Branch", "Street", "St_number", "City", "ADMIN_FNAME", "ADMIN_LNAME", "Reservations", "Total_Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setPreferredSize(new java.awt.Dimension(500, 80));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(false);
        jScrollPane3.setViewportView(jTable1);

        btnRESETbr.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 810, 100));

        btnClrTbls.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnClrTbls.setText("CLEAR TABLES");
        btnClrTbls.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClrTbls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClrTblsActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnClrTbls, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 640, 120, 40));

        bntProfCos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        bntProfCos.setText("PROFITS/COSTS");
        bntProfCos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntProfCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntProfCosActionPerformed(evt);
            }
        });
        btnRESETbr.add(bntProfCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 590, 120, 30));

        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "br_code", "Total_Ammount", "Total_Payout"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);

        btnRESETbr.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 290, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRESETbr, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRESETbr, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnbrActionPerformed
        // TODO add your handling code here:
        IT_operationsFrame s = new IT_operationsFrame();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturnbrActionPerformed

    private void brcodetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brcodetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brcodetxtActionPerformed

    private void btnResetbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetbrActionPerformed
        // TODO add your handling code here:
        brcodetxt.setText("");
        brnumtxt.setText("");
        brcitytxt.setText("");
        brstreettxt.setText("");
    }//GEN-LAST:event_btnResetbrActionPerformed

    private void brstreettxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brstreettxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brstreettxtActionPerformed

    private void brnumtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnumtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brnumtxtActionPerformed

    private void brcitytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brcitytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brcitytxtActionPerformed

    private void btnUPDATEbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEbrActionPerformed
        // TODO add your handling code here:
        try{
            updateAddDelBranch();
            
             if(!(brstreet.isEmpty()) && brnum.isEmpty() && brcity.isEmpty()){
                ps = sqlConn.prepareStatement("UPDATE branch set br_street=? WHERE br_code=?");
                ps.setString(2, brcode);
                ps.setString(1, brstreet);
                ps.executeUpdate();
            }else if(brstreet.isEmpty() && !(brnum.isEmpty()) && brcity.isEmpty()){
                ps = sqlConn.prepareStatement("UPDATE branch set br_num=? WHERE br_code=?");
                ps.setString(2, brcode);
                ps.setString(1, brnum);
                ps.executeUpdate();
            }else if(brstreet.isEmpty() && brnum.isEmpty() && !(brcity.isEmpty())){
                ps = sqlConn.prepareStatement("UPDATE branch set br_city=? WHERE br_code=?");
                ps.setString(2, brcode);
                ps.setString(1, brcity);
                ps.executeUpdate();
            }else{
                ps = sqlConn.prepareStatement("UPDATE branch set br_street=?,br_num=?,br_city=? WHERE br_code=?");
                ps.setString(1,brstreet);
                ps.setString(2, brnum);
                ps.setString(3, brcity);
                ps.setString(4, brcode);
                ps.executeUpdate();
            }
             
            JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
        }catch(Exception e){
            //java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
            JOptionPane.showMessageDialog(null, e);
        }
    
    }//GEN-LAST:event_btnUPDATEbrActionPerformed

    private void btnADDbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDbrActionPerformed
        // TODO add your handling code here:
        try{
            updateAddDelBranch();
            
            ps = sqlConn.prepareStatement("insert into branch(br_code,br_street,br_num,br_city)values(?,?,?,?)");

            ps.setString(1, brcode);
            ps.setString(2,brstreet);
            ps.setString(3, brnum);
            ps.setString(4,brcity);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Added Successfully!");
        }catch(java.sql.SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnADDbrActionPerformed

    private void btnDELETEbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEbrActionPerformed
        // TODO add your handling code here:
        try{
            updateAddDelBranch();
            
           if(!(brstreet.isEmpty()) && brnum.isEmpty() && brcity.isEmpty()){
                ps = sqlConn.prepareStatement("DELETE FROM branch WHERE br_code=? AND (br_street LIKE ?)");
                ps.setString(1, brcode);
                ps.setString(2, brstreet);
                ps.executeUpdate();
            }else if(brstreet.isEmpty() && !(brnum.isEmpty()) && brcity.isEmpty()){
                ps = sqlConn.prepareStatement("DELETE FROM branch WHERE (br_num LIKE ?) AND br_code=?");
                ps.setString(2, brcode);
                ps.setString(1, brnum);
                ps.executeUpdate();
            }else if(brstreet.isEmpty() && brnum.isEmpty() && !(brcity.isEmpty())){
                ps = sqlConn.prepareStatement("DELETE FROM branch WHERE (br_city LIKE ?) AND br_code=?");
                ps.setString(2, brcode);
                ps.setString(1, brcity);
                ps.executeUpdate();
            }else{
                ps = sqlConn.prepareStatement("DELETE FROM branch WHERE br_code=?");
                ps.setString(1,brcode);
                ps.executeUpdate();
            }
           
            JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
        }catch(java.sql.SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnDELETEbrActionPerformed

    private void btnBRANCHINFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBRANCHINFOActionPerformed
        // TODO add your handling code here:
        try{
            sqlConn = DriverManager.getConnection(dataB,username,password);
            CallableStatement cs = sqlConn.prepareCall("{call branch_info(?)}");
            cs.setString(1, brcodetxt.getText());
            ResultSet rs = cs.executeQuery();
            
            DefaultTableModel model = new DefaultTableModel();
            jTable1.setModel(model);
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();
            
            for (int i = 1; i <= columnCount; i++) {
                model.addColumn(metaData.getColumnLabel(i));
            }
            
            while (rs.next()) {
                Object[] rowData = new Object[columnCount];
                for (int i = 1; i <= columnCount; i++) {
                    rowData[i - 1] = rs.getObject(i);
                }
                model.addRow(rowData);
            }
            cs.close();
            sqlConn.close();
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnBRANCHINFOActionPerformed

    private void btnBRANCHTABLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBRANCHTABLEActionPerformed
        // TODO add your handling code here:
         Table b = new Table();
         b.setVisible(true);
    }//GEN-LAST:event_btnBRANCHTABLEActionPerformed

    private void btnEMPLOYEEINFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEMPLOYEEINFOActionPerformed
        // TODO add your handling code here:
        try{
            sqlConn = DriverManager.getConnection(dataB,username,password);
            CallableStatement cs = sqlConn.prepareCall("{call employee_info(?)}");
            cs.setString(1, brcodetxt.getText());
            ResultSet rs = cs.executeQuery();
            
            DefaultTableModel model = new DefaultTableModel();
            jTable.setModel(model);
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();
            
            for (int i = 1; i <= columnCount; i++) {
                model.addColumn(metaData.getColumnLabel(i));
            }
            
            while (rs.next()) {
                Object[] rowData = new Object[columnCount];
                for (int i = 1; i <= columnCount; i++) {
                    rowData[i - 1] = rs.getObject(i);
                }
                model.addRow(rowData);
            }
            cs.close();
            sqlConn.close();
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnEMPLOYEEINFOActionPerformed

    private void btnClrTblsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClrTblsActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable.getModel();
        model.setRowCount(0);
        
        DefaultTableModel model1 = (DefaultTableModel)jTable1.getModel();
        model1.setRowCount(0);
        
        DefaultTableModel model2 = (DefaultTableModel)jTable2.getModel();
        model2.setRowCount(0);
    }//GEN-LAST:event_btnClrTblsActionPerformed

    private void bntProfCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntProfCosActionPerformed
        // TODO add your handling code here:
        try{
            sqlConn = DriverManager.getConnection(dataB,username,password);
            CallableStatement cs = sqlConn.prepareCall("{call total_bonus(?)}");
            cs.setString(1, brcodetxt.getText());
            ResultSet rs = cs.executeQuery();
            
            DefaultTableModel model = new DefaultTableModel();
            jTable2.setModel(model);
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();
            
            for (int i = 1; i <= columnCount; i++) {
                model.addColumn(metaData.getColumnLabel(i));
            }
            
            while (rs.next()) {
                Object[] rowData = new Object[columnCount];
                for (int i = 1; i <= columnCount; i++) {
                    rowData[i - 1] = rs.getObject(i);
                }
                model.addRow(rowData);
            }
            cs.close();
            sqlConn.close();
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_bntProfCosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new branchFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntProfCos;
    private javax.swing.JTextField brcitytxt;
    private javax.swing.JTextField brcodetxt;
    private javax.swing.JTextField brnumtxt;
    private javax.swing.JTextField brstreettxt;
    private javax.swing.JButton btnADDbr;
    private javax.swing.JButton btnBRANCHINFO;
    private javax.swing.JButton btnBRANCHTABLE;
    private javax.swing.JButton btnClrTbls;
    private javax.swing.JButton btnDELETEbr;
    private javax.swing.JButton btnEMPLOYEEINFO;
    private javax.swing.JPanel btnRESETbr;
    private javax.swing.JButton btnResetbr;
    private javax.swing.JButton btnReturnbr;
    private javax.swing.JButton btnUPDATEbr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
