
package projectdb_2022_23;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;

public class destinationFrame extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String password = "123456";
    private static final String dataB = "jdbc:mysql://localhost:3306/travel_agency";
    
    Connection sqlConn = null;
    PreparedStatement ps = null;
    
    String dstID = null;
    String name = null;
    String descr = null;
    String type = null;
    String lng = null;
    String loc = null;
    int flag;
    public destinationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     public void updateAddDelDestination(){
        try{
             dstID = dstidtxt.getText();
             name = dstNametxt.getText();
             descr = dstdescrtxt.getText();
             type = dstTypetxt.getText();
             lng = dstLngtxt.getText();
             loc = dstLoctxt.getText();
             
             if(!(name.isEmpty()) && descr.isEmpty() && type.isEmpty() && lng.isEmpty() && loc.isEmpty())
                 flag = 1;
             else if(name.isEmpty() && !(descr.isEmpty()) && type.isEmpty() && lng.isEmpty() && loc.isEmpty())
                 flag = 2;
             else if(name.isEmpty() && descr.isEmpty() && !(type.isEmpty()) && lng.isEmpty() && loc.isEmpty())
                 flag = 3;
             else if(name.isEmpty() && descr.isEmpty() && type.isEmpty() && !(lng.isEmpty()) && loc.isEmpty())
                 flag = 4;
             else if(name.isEmpty() && descr.isEmpty() && type.isEmpty() && lng.isEmpty() && !(loc.isEmpty()))
                 flag = 5;
             else
                 flag = 0;
 
             Class.forName("com.mysql.jdbc.Driver");
             sqlConn = DriverManager.getConnection(dataB,username,password);
        }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, e);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRESETbr = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnReturnbr = new javax.swing.JButton();
        dstidtxt = new javax.swing.JTextField();
        btnUPDATEdst = new javax.swing.JButton();
        btnADDdst = new javax.swing.JButton();
        btnResetdst = new javax.swing.JButton();
        btnDELETEdst = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dstNametxt = new javax.swing.JTextField();
        dstdescrtxt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        dstTypetxt = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        dstLngtxt = new javax.swing.JTextField();
        btnDestinationTABLE = new javax.swing.JButton();
        dstLoctxt = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRESETbr.setBackground(new java.awt.Color(0, 0, 0));
        btnRESETbr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 8));
        btnRESETbr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Destination Table");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 380, 70));

        btnReturnbr.setFont(new java.awt.Font("Segoe UI Semibold", 1, 26)); // NOI18N
        btnReturnbr.setText("Return");
        btnReturnbr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReturnbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnbrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnReturnbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 700, 130, 50));

        dstidtxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        dstidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dstidtxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(dstidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 460, 30));

        btnUPDATEdst.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnUPDATEdst.setText("UPDATE");
        btnUPDATEdst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUPDATEdst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEdstActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnUPDATEdst, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, 130, 50));

        btnADDdst.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnADDdst.setText("ADD");
        btnADDdst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnADDdst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDdstActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnADDdst, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, 130, 50));

        btnResetdst.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnResetdst.setText("RESET");
        btnResetdst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetdst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetdstActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnResetdst, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, 130, 50));

        btnDELETEdst.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnDELETEdst.setText("DELETE");
        btnDELETEdst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDELETEdst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEdstActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnDELETEdst, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 340, 130, 50));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("destination id");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, 30));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("destination name");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 210, 30));

        dstNametxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        dstNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dstNametxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(dstNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 460, 30));

        dstdescrtxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        dstdescrtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dstdescrtxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(dstdescrtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 460, 30));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 0));
        jLabel8.setText("destination type");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 190, -1));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("description");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 180, -1));

        dstTypetxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        dstTypetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dstTypetxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(dstTypetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 460, 30));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setText("destination language");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 230, -1));

        dstLngtxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        dstLngtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dstLngtxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(dstLngtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 460, 30));

        btnDestinationTABLE.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDestinationTABLE.setText("DESTINATION TABLE");
        btnDestinationTABLE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDestinationTABLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDestinationTABLEActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnDestinationTABLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, 160, 60));

        dstLoctxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        dstLoctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dstLoctxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(dstLoctxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 460, 30));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 0));
        jLabel9.setText("location");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 170, -1));

        getContentPane().add(btnRESETbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnbrActionPerformed
        // TODO add your handling code here:
        IT_operationsFrame s = new IT_operationsFrame();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturnbrActionPerformed

    private void dstidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dstidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dstidtxtActionPerformed

    private void btnUPDATEdstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEdstActionPerformed
        // TODO add your handling code here:

        try{
            updateAddDelDestination();

            switch(flag){
                case 0:
                ps = sqlConn.prepareStatement("UPDATE destination set dst_name=?,dst_descr=?,dst_rtype=?,dst_language=?,dst_location=? WHERE dst_id=?");
                ps.setString(1, name);
                ps.setString(2, descr);
                ps.setString(3, type);
                ps.setString(4, lng);
                ps.setString(5, loc);
                ps.setString(6, dstID);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                case 1:
                ps = sqlConn.prepareStatement("UPDATE destination set dst_name=? WHERE dst_id=?");
                ps.setString(2, dstID);
                ps.setString(1, name);
                ps.executeUpdate();
                case 2:
                ps = sqlConn.prepareStatement("UPDATE destination set dst_descr=? WHERE dst_id=?");
                ps.setString(2, dstID);
                ps.setString(1, descr);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                case 3:
                    ps = sqlConn.prepareStatement("UPDATE destination set dst_rtype=? WHERE dst_id=?");
                    ps.setString(2, dstID);
                    ps.setString(1, type);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                case 4:
                ps = sqlConn.prepareStatement("UPDATE destination set dst_language=? WHERE dst_id=?");
                ps.setString(2, dstID);
                ps.setString(1, lng);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                case 5:
                ps = sqlConn.prepareStatement("UPDATE destination set dst_location=? WHERE dst_id=?");
                ps.setString(2, dstID);
                ps.setString(1, loc);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
            }

        }catch(Exception e){
            //java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
            System.out.println(e);
        }
    }//GEN-LAST:event_btnUPDATEdstActionPerformed

    private void btnADDdstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDdstActionPerformed
        // TODO add your handling code here:

        try{
            updateAddDelDestination();

            ps = sqlConn.prepareStatement("insert into destination(dst_id,dst_name,dst_descr,dst_rtype,dst_language,dst_location)values(?,?,?,?,?,?)");

            ps.setString(1, dstID);
            ps.setString(2,name);
            ps.setString(3, descr);
            ps.setString(4, type);
            ps.setString(5, lng);
            ps.setString(6, loc);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Added Successfully!");
        }catch(Exception e){
            //java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnADDdstActionPerformed

    private void btnResetdstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetdstActionPerformed
        // TODO add your handling code here:
        dstidtxt.setText("");
        dstdescrtxt.setText("");
        dstTypetxt.setText("");
        dstNametxt.setText("");
        dstLngtxt.setText("");
        dstLoctxt.setText("");
    }//GEN-LAST:event_btnResetdstActionPerformed

    private void btnDELETEdstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEdstActionPerformed
        // TODO add your handling code here:

        try{
            updateAddDelDestination();

            switch(flag){
                case 0:
                ps = sqlConn.prepareStatement("DELETE FROM destination WHERE dst_id=?");
                ps.setString(1, dstID);
                ps.executeUpdate();
                case 1:
                ps = sqlConn.prepareStatement("DELETE FROM destination WHERE dst_id=? AND (dst_name LIKE ?)");
                ps.setString(1, dstID);
                ps.setString(2, name);
                ps.executeUpdate();
                case 2:
                ps = sqlConn.prepareStatement("DELETE FROM destination WHERE dst_id=? AND (dst_descr LIKE ?)");
                ps.setString(1, dstID);
                ps.setString(2, descr);
                ps.executeUpdate();
                case 3:
                ps = sqlConn.prepareStatement("DELETE FROM destination WHERE dst_id=? AND (dst_rtype LIKE ?)");
                ps.setString(1, dstID);
                ps.setString(2, type);
                ps.executeUpdate();
                case 4:
                ps = sqlConn.prepareStatement("DELETE FROM destination WHERE dst_id=? AND (dst_language LIKE ?)");
                ps.setString(1, dstID);
                ps.setString(2, lng);
                ps.executeUpdate();
                case 5:
                ps = sqlConn.prepareStatement("DELETE FROM destination WHERE dst_id=? AND (dst_location=?)");
                ps.setString(1, dstID);
                ps.setString(2, loc);
                ps.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
        }catch(Exception e){
            //java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnDELETEdstActionPerformed

    private void dstNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dstNametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dstNametxtActionPerformed

    private void dstdescrtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dstdescrtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dstdescrtxtActionPerformed

    private void dstTypetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dstTypetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dstTypetxtActionPerformed

    private void dstLngtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dstLngtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dstLngtxtActionPerformed

    private void btnDestinationTABLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestinationTABLEActionPerformed
        // TODO add your handling code here:
        Tabledestination Tdst = new Tabledestination();
        Tdst.setVisible(true);
    }//GEN-LAST:event_btnDestinationTABLEActionPerformed

    private void dstLoctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dstLoctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dstLoctxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(destinationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(destinationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(destinationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(destinationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new destinationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADDdst;
    private javax.swing.JButton btnDELETEdst;
    private javax.swing.JButton btnDestinationTABLE;
    private javax.swing.JPanel btnRESETbr;
    private javax.swing.JButton btnResetdst;
    private javax.swing.JButton btnReturnbr;
    private javax.swing.JButton btnUPDATEdst;
    private javax.swing.JTextField dstLngtxt;
    private javax.swing.JTextField dstLoctxt;
    private javax.swing.JTextField dstNametxt;
    private javax.swing.JTextField dstTypetxt;
    private javax.swing.JTextField dstdescrtxt;
    private javax.swing.JTextField dstidtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
