
package projectdb_2022_23;

import javax.swing.JOptionPane;


public class IT_operationsFrame extends javax.swing.JFrame {

    
            
    public IT_operationsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPhones = new javax.swing.JButton();
        btnManages = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnBranch = new javax.swing.JButton();
        btnIT = new javax.swing.JButton();
        btnDriver = new javax.swing.JButton();
        btnReservation = new javax.swing.JButton();
        btnEXIT = new javax.swing.JButton();
        btnDestination = new javax.swing.JButton();
        btnLanguages = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnEvent = new javax.swing.JButton();
        btnWorker = new javax.swing.JButton();
        btnGuide = new javax.swing.JButton();
        btnTravel_to = new javax.swing.JButton();
        btnTrip = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnLOGOUT = new javax.swing.JButton();
        btnOffers = new javax.swing.JButton();
        btrnResOffers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 8));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Welcome to IT Panel");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 400, 70));

        btnPhones.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnPhones.setText("phones");
        btnPhones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPhones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhonesActionPerformed(evt);
            }
        });
        jPanel1.add(btnPhones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 110, 40));

        btnManages.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnManages.setText("manages");
        btnManages.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagesActionPerformed(evt);
            }
        });
        jPanel1.add(btnManages, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 110, 40));

        jButton6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton6.setText("phones");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 110, 40));

        btnBranch.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnBranch.setText("branch");
        btnBranch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBranchActionPerformed(evt);
            }
        });
        jPanel1.add(btnBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 110, 40));

        btnIT.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnIT.setText("IT");
        btnIT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnITActionPerformed(evt);
            }
        });
        jPanel1.add(btnIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, 110, 40));

        btnDriver.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnDriver.setText("driver");
        btnDriver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDriverActionPerformed(evt);
            }
        });
        jPanel1.add(btnDriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 110, 40));

        btnReservation.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnReservation.setText("reservation");
        btnReservation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservationActionPerformed(evt);
            }
        });
        jPanel1.add(btnReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 130, 40));

        btnEXIT.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnEXIT.setText("EXIT");
        btnEXIT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEXITActionPerformed(evt);
            }
        });
        jPanel1.add(btnEXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, 200, 60));

        btnDestination.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnDestination.setText("destination");
        btnDestination.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDestinationActionPerformed(evt);
            }
        });
        jPanel1.add(btnDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 130, 40));

        btnLanguages.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnLanguages.setText("languages");
        btnLanguages.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLanguages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanguagesActionPerformed(evt);
            }
        });
        jPanel1.add(btnLanguages, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 130, 40));

        btnAdmin.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnAdmin.setText("admin");
        btnAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 110, 40));

        jButton5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton5.setText("branch");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 110, 40));

        btnEvent.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnEvent.setText("event");
        btnEvent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventActionPerformed(evt);
            }
        });
        jPanel1.add(btnEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 110, 40));

        btnWorker.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnWorker.setText("worker");
        btnWorker.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkerActionPerformed(evt);
            }
        });
        jPanel1.add(btnWorker, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 110, 40));

        btnGuide.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnGuide.setText("guide");
        btnGuide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuideActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuide, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 110, 40));

        btnTravel_to.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnTravel_to.setText("travel_to");
        btnTravel_to.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTravel_to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTravel_toActionPerformed(evt);
            }
        });
        jPanel1.add(btnTravel_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 110, 40));

        btnTrip.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnTrip.setText("trip");
        btnTrip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTripActionPerformed(evt);
            }
        });
        jPanel1.add(btnTrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 110, 40));

        btnLog.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnLog.setText("log");
        btnLog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });
        jPanel1.add(btnLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 200, 60));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 2, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("Please Select a Table To Perform Operations");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 350, 40));

        btnLOGOUT.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnLOGOUT.setText("LOGOUT");
        btnLOGOUT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLOGOUTActionPerformed(evt);
            }
        });
        jPanel1.add(btnLOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 670, 200, 60));

        btnOffers.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnOffers.setText("offers");
        btnOffers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOffers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOffersActionPerformed(evt);
            }
        });
        jPanel1.add(btnOffers, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, 110, 40));

        btrnResOffers.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btrnResOffers.setText("reservation offers");
        btrnResOffers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btrnResOffers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrnResOffersActionPerformed(evt);
            }
        });
        jPanel1.add(btrnResOffers, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 200, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEXITActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Are you sure you want to Exit?","EXIT",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnEXITActionPerformed

    private void btnEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventActionPerformed
        // TODO add your handling code here:
        eventFrame evf = new eventFrame();
        evf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEventActionPerformed

    private void btnBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBranchActionPerformed
        // TODO add your handling code here:
        branchFrame bf = new branchFrame();
        bf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBranchActionPerformed

    private void btnLOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLOGOUTActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Are you sure you want to Logout?",
                "LOGOUT",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.dispose();
            IT_loginFrame s = new IT_loginFrame();
            s.setVisible(true);
        }
    }//GEN-LAST:event_btnLOGOUTActionPerformed

    private void btnPhonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhonesActionPerformed
        // TODO add your handling code here:
        phonesFrame pf = new phonesFrame();
        pf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPhonesActionPerformed

    private void btnManagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagesActionPerformed
        // TODO add your handling code here:
        managesFrame maf = new managesFrame();
        maf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManagesActionPerformed

    private void btnDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDriverActionPerformed
        // TODO add your handling code here:
        driverFrame dr = new driverFrame();
        dr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDriverActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        
        adminFrame ad = new adminFrame();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkerActionPerformed
        // TODO add your handling code here:
        
        workerFrame wf = new workerFrame();
        wf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnWorkerActionPerformed

    private void btnGuideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuideActionPerformed
        // TODO add your handling code here:
        guideFrame gf = new guideFrame();
        gf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGuideActionPerformed

    private void btnLanguagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanguagesActionPerformed
        // TODO add your handling code here:
        languagesFrame lngf = new languagesFrame();
        lngf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLanguagesActionPerformed

    private void btnTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTripActionPerformed
        // TODO add your handling code here:
        tripFrame tf = new tripFrame();
        tf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTripActionPerformed

    private void btnTravel_toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTravel_toActionPerformed
        // TODO add your handling code here:
        travel_toFrame tra = new travel_toFrame();
        tra.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTravel_toActionPerformed

    private void btnDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestinationActionPerformed
        // TODO add your handling code here:
        destinationFrame dstf = new destinationFrame();
        dstf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDestinationActionPerformed

    private void btnReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservationActionPerformed
        // TODO add your handling code here:
        reservationFrame resf = new reservationFrame();
        resf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReservationActionPerformed

    private void btnITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnITActionPerformed
        // TODO add your handling code here:
        itFrame it = new itFrame();
        it.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnITActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:
        logFrame log = new logFrame();
        log.setVisible(true);
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnOffersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOffersActionPerformed
        // TODO add your handling code here:
        offersFrame ofFr = new offersFrame();
        ofFr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOffersActionPerformed

    private void btrnResOffersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrnResOffersActionPerformed
        // TODO add your handling code here:
        reservationOffersFrame resOf = new reservationOffersFrame();
        resOf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btrnResOffersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IT_operationsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IT_operationsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IT_operationsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IT_operationsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IT_operationsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnBranch;
    private javax.swing.JButton btnDestination;
    private javax.swing.JButton btnDriver;
    private javax.swing.JButton btnEXIT;
    private javax.swing.JButton btnEvent;
    private javax.swing.JButton btnGuide;
    private javax.swing.JButton btnIT;
    private javax.swing.JButton btnLOGOUT;
    private javax.swing.JButton btnLanguages;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnManages;
    private javax.swing.JButton btnOffers;
    private javax.swing.JButton btnPhones;
    private javax.swing.JButton btnReservation;
    private javax.swing.JButton btnTravel_to;
    private javax.swing.JButton btnTrip;
    private javax.swing.JButton btnWorker;
    private javax.swing.JButton btrnResOffers;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
