
package projectdb_2022_23;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

public class itFrame extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String password = "123456";
    private static final String dataB = "jdbc:mysql://localhost:3306/travel_agency";
    
    Connection sqlConn = null;
    PreparedStatement ps = null;
    
    String itAT = null;
    String itpass = null;
    String itstart = null;
    String itend = null;
    java.sql.Date sqldob = null;
    java.sql.Date sqldob2 = null;
    
    public itFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
         public void updateAddDelIT(){
            try{
                 itAT = itATtxt.getText();
                 itpass = itPasstxt.getText();
                 itstart = itStarttxt.getText();
                 itend = itEndtxt.getText();

                 Class.forName("com.mysql.jdbc.Driver");
                 sqlConn = DriverManager.getConnection(dataB,username,password);
            }catch(ClassNotFoundException e){
                JOptionPane.showMessageDialog(null, e);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRESETbr = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnReturntra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        itATtxt = new javax.swing.JTextField();
        btnUPDATEtra = new javax.swing.JButton();
        btnADDtra = new javax.swing.JButton();
        btnResettra = new javax.swing.JButton();
        btnDELETEtra = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        itPasstxt = new javax.swing.JTextField();
        itStarttxt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        itEndtxt = new javax.swing.JTextField();
        btnViewtra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRESETbr.setBackground(new java.awt.Color(0, 0, 0));
        btnRESETbr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 8));
        btnRESETbr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("IT   Table");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 300, 70));

        btnReturntra.setFont(new java.awt.Font("Segoe UI Semibold", 1, 26)); // NOI18N
        btnReturntra.setText("Return");
        btnReturntra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReturntra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturntraActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnReturntra, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 670, 130, 50));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "it_AT", "it_password", "start_date", "end_date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnRESETbr.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 800, 250));

        itATtxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        itATtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itATtxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(itATtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 460, 30));

        btnUPDATEtra.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnUPDATEtra.setText("UPDATE");
        btnUPDATEtra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUPDATEtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEtraActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnUPDATEtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, 130, 50));

        btnADDtra.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnADDtra.setText("ADD");
        btnADDtra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnADDtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDtraActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnADDtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 160, 130, 50));

        btnResettra.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnResettra.setText("RESET");
        btnResettra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResettra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResettraActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnResettra, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 370, 130, 50));

        btnDELETEtra.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnDELETEtra.setText("DELETE");
        btnDELETEtra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDELETEtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEtraActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnDELETEtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 300, 130, 50));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("IT AT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 170, 30));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("Password");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 160, -1));

        itPasstxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        itPasstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itPasstxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(itPasstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 460, 30));

        itStarttxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        itStarttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itStarttxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(itStarttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 460, 30));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("end date");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 160, -1));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("start date");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 160, -1));

        itEndtxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        itEndtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itEndtxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(itEndtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 460, 30));

        btnViewtra.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnViewtra.setText("View Data");
        btnViewtra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewtraActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnViewtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, 130, 40));

        getContentPane().add(btnRESETbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturntraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturntraActionPerformed
        // TODO add your handling code here:
        IT_operationsFrame s = new IT_operationsFrame();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturntraActionPerformed

    private void itATtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itATtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itATtxtActionPerformed

    private void btnUPDATEtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEtraActionPerformed
        // TODO add your handling code here:

        try{
            updateAddDelIT();

            if(!(itpass.isEmpty()) && itstart.isEmpty() && itend.isEmpty()){
                ps = sqlConn.prepareStatement("UPDATE it set it_password=? WHERE it_AT=?");
                ps.setString(1, itpass);
                ps.setString(2, itAT);
                ps.executeUpdate();
            }else if(itpass.isEmpty() && !(itstart.isEmpty()) && itend.isEmpty()){
                ps = sqlConn.prepareStatement("UPDATE it set start_date=? WHERE it_AT=?");
                ps.setString(1, itstart);
                ps.setString(2, itAT);
                ps.executeUpdate();
            }else if(itpass.isEmpty() && itstart.isEmpty() && !(itend.isEmpty())){
                ps = sqlConn.prepareStatement("UPDATE it set end_date=? WHERE it_AT=?");
                ps.setString(1, itend);
                ps.setString(2, itAT);
                ps.executeUpdate();
            }else{
                ps = sqlConn.prepareStatement("UPDATE it set it_password=?,start_date=?,end_date? WHERE it_AT=?");
                ps.setString(4,itAT);
                ps.setString(1, itpass);
                ps.setString(2, itstart);
                ps.setString(3, itend);
                ps.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
        }catch(Exception e){
            //java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnUPDATEtraActionPerformed

    private void btnADDtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDtraActionPerformed
        // TODO add your handling code here:
        try{
            updateAddDelIT();
            if(!(itend.isEmpty())){
                 if(!(itpass.isEmpty())){
                    ps = sqlConn.prepareStatement("insert into it(it_AT,it_password,start_date,end_date)values(?,?,?,?)");
                    ps.setString(1, itAT);
                    ps.setString(2,itpass);
                    ps.setString(3, itstart);
                    ps.setString(4, itend);
                }else{
                    ps = sqlConn.prepareStatement("insert into it(it_AT,it_password,start_date,end_date)values(?,default,?,?)");
                    ps.setString(1, itAT);
                    ps.setString(2, itstart);
                    ps.setString(3, itend);
                }
            }else{
                if(!(itpass.isEmpty())){
                    ps = sqlConn.prepareStatement("insert into it(it_AT,it_password,start_date,end_date)values(?,?,?,null)");
                    ps.setString(1, itAT);
                    ps.setString(2,itpass);
                    ps.setString(3, itstart);
                }else{
                    ps = sqlConn.prepareStatement("insert into it(it_AT,it_password,start_date,end_date)values(?,default,?,null)");
                    ps.setString(1, itAT);
                    ps.setString(2, itstart);
                }
            }   
            ps.executeUpdate();
            itATtxt.setText("");
            itStarttxt.setText("");
            itEndtxt.setText("");
            itPasstxt.setText("");
            JOptionPane.showMessageDialog(this, "Added Successfully!");
        }catch(Exception e){
            //java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnADDtraActionPerformed

    private void btnResettraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResettraActionPerformed
        // TODO add your handling code here:
        itATtxt.setText("");
        itStarttxt.setText("");
        itEndtxt.setText("");
        itPasstxt.setText("");
    }//GEN-LAST:event_btnResettraActionPerformed

    private void btnDELETEtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEtraActionPerformed
        // TODO add your handling code here:

        try{
            updateAddDelIT();

            if(!(itpass.isEmpty()) && itstart.isEmpty() && itend.isEmpty()){
                ps = sqlConn.prepareStatement("DELETE FROM it WHERE (it_AT LIKE ?) AND (it_password LIKE ?)");
                ps.setString(1, itAT);
                ps.setString(2, itpass);
                ps.executeUpdate();
            }else if(itpass.isEmpty() && !(itstart.isEmpty()) && itend.isEmpty()){
                ps = sqlConn.prepareStatement("DELETE FROM it WHERE (it_AT LIKE ?) AND (start_date=?)");
                ps.setString(1, itAT);
                ps.setString(2, itstart);
                ps.executeUpdate();
            }else if(itpass.isEmpty() && itstart.isEmpty() && !(itend.isEmpty())){
                ps = sqlConn.prepareStatement("DELETE FROM it WHERE (it_AT LIKE ?) AND (end_date=?)");
                ps.setString(1, itAT);
                ps.setString(2, itend);
                ps.executeUpdate();
            }else{
                ps = sqlConn.prepareStatement("DELETE FROM it WHERE (it_AT LIKE ?)");
                ps.setString(1, itAT);
                ps.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
        }catch(Exception e){
            //java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
            System.out.print(e);
        }
    }//GEN-LAST:event_btnDELETEtraActionPerformed

    private void itPasstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itPasstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itPasstxtActionPerformed

    private void itStarttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itStarttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itStarttxtActionPerformed

    private void itEndtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itEndtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itEndtxtActionPerformed

    private void btnViewtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewtraActionPerformed
        // TODO add your handling code here:
        try{

            sqlConn = DriverManager.getConnection(dataB,username,password);
            PreparedStatement pst = sqlConn.prepareStatement("SELECT * FROM it");
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnViewtraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(itFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(itFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(itFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(itFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new itFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADDtra;
    private javax.swing.JButton btnDELETEtra;
    private javax.swing.JPanel btnRESETbr;
    private javax.swing.JButton btnResettra;
    private javax.swing.JButton btnReturntra;
    private javax.swing.JButton btnUPDATEtra;
    private javax.swing.JButton btnViewtra;
    private javax.swing.JTextField itATtxt;
    private javax.swing.JTextField itEndtxt;
    private javax.swing.JTextField itPasstxt;
    private javax.swing.JTextField itStarttxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
