
package projectdb_2022_23;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class reservationOffersFrame extends javax.swing.JFrame {
    private static final String username = "root";
    private static final String password = "123456";
    private static final String dataB = "jdbc:mysql://localhost:3306/travel_agency";
    
    Connection sqlConn = null;
    PreparedStatement ps = null;
    
    String resofid = null;
    String clname = null;
    String cname = null;
    String pay = null;
    int column;
    int row;
    String Row=null;


    int flag;
    
    public reservationOffersFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     public void updateAddDelResOffers(){
        try{
             resofid = resofidtxt.getText();
             clname = clnametxt.getText();
             cname = cnametxt.getText();
             pay = paytxt.getText();
             column = 0;
             row = jTable1.getSelectedRow(); 
             Row = jTable1.getModel().getValueAt(row, column).toString();
             
             if(!(clname.isEmpty()) && cname.isEmpty() && pay.isEmpty())
                 flag = 1;
             else if(clname.isEmpty() && !(cname.isEmpty()) && pay.isEmpty())
                 flag = 2;
             else if(clname.isEmpty() && cname.isEmpty() && !(pay.isEmpty()))
                 flag = 3;
             else
                 flag = 0;
             
 
             Class.forName("com.mysql.jdbc.Driver");
             sqlConn = DriverManager.getConnection(dataB,username,password);
        }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, e);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRESETbr = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnReturnre = new javax.swing.JButton();
        resofidtxt = new javax.swing.JTextField();
        btnUPDATEre = new javax.swing.JButton();
        btnADDre = new javax.swing.JButton();
        btnResetre = new javax.swing.JButton();
        btnDELETEre = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        clnametxt = new javax.swing.JTextField();
        cnametxt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        paytxt = new javax.swing.JTextField();
        btnResoffersTABLE = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRESETbr.setBackground(new java.awt.Color(0, 0, 0));
        btnRESETbr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 8));
        btnRESETbr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Reservation Offers Table");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 490, 70));

        btnReturnre.setFont(new java.awt.Font("Segoe UI Semibold", 1, 26)); // NOI18N
        btnReturnre.setText("Return");
        btnReturnre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReturnre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnreActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnReturnre, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 720, 130, 50));

        resofidtxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        resofidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resofidtxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(resofidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 460, 30));

        btnUPDATEre.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnUPDATEre.setText("UPDATE");
        btnUPDATEre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUPDATEre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEreActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnUPDATEre, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, 130, 50));

        btnADDre.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnADDre.setText("ADD");
        btnADDre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnADDre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDreActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnADDre, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 250, 130, 50));

        btnResetre.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnResetre.setText("RESET");
        btnResetre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetreActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnResetre, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, 130, 50));

        btnDELETEre.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnDELETEre.setText("DELETE");
        btnDELETEre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDELETEre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEreActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnDELETEre, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, 130, 50));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("reservation offer id");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 210, 30));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("customer's Lastname");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnRESETbr.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 220, 30));

        clnametxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        clnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clnametxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(clnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 460, 30));

        cnametxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        cnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnametxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(cnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 460, 30));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 0));
        jLabel8.setText("offer id");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 120, -1));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("customer's Name");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 200, -1));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setText("payment in advance");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 220, -1));

        paytxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        paytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paytxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(paytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 460, 30));

        btnResoffersTABLE.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnResoffersTABLE.setText("SHOW OFFERS' IDs");
        btnResoffersTABLE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResoffersTABLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResoffersTABLEActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnResoffersTABLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 640, 220, 80));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "offer id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        btnRESETbr.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 180, 210));

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        jButton1.setText("RESERVATION OFFERS");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        btnRESETbr.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 570, 200, 60));

        getContentPane().add(btnRESETbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnreActionPerformed
        // TODO add your handling code here:
        IT_operationsFrame s = new IT_operationsFrame();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturnreActionPerformed

    private void resofidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resofidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resofidtxtActionPerformed

    private void btnUPDATEreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEreActionPerformed
        // TODO add your handling code here:

        try{
            updateAddDelResOffers();

            switch(flag){
                case 0:
                    ps = sqlConn.prepareStatement("UPDATE reservation_offers set customer_lname=?,customer_name=?,off_id=?,payment_in_advance=? WHERE reservation_offer_id=?");
                    ps.setString(1, clname);
                    ps.setString(2, cname);
                    ps.setString(3, pay);
                    ps.setString(4, Row);
                    ps.setString(5, resofid);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                case 1:
                    ps = sqlConn.prepareStatement("UPDATE reservation_offers set customer_lname=? WHERE reservation_offer_id=?");
                    ps.setString(2, resofid);
                    ps.setString(1, clname);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                case 2:
                    ps = sqlConn.prepareStatement("UPDATE reservation_offers set customer_name=? WHERE reservation_offer_id=?");
                    ps.setString(2, resofid);
                    ps.setString(1, cname);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                case 3:
                    ps = sqlConn.prepareStatement("UPDATE reservation_offers set payment_in_advance=? WHERE reservation_offer_id=?");
                    ps.setString(2, resofid);
                    ps.setString(1, pay);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
            }

        }catch(Exception e){
            //java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
            System.out.println(e);
        }
    }//GEN-LAST:event_btnUPDATEreActionPerformed

    private void btnADDreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDreActionPerformed
        // TODO add your handling code here:

        try{
            updateAddDelResOffers();

            ps = sqlConn.prepareStatement("insert into reservation_offers(reservation_offer_id,customer_lname,customer_name,off_id,payment_in_advance)values(?,?,?,?,?)");

            ps.setString(1, resofid);
            ps.setString(2,clname);
            ps.setString(3, cname);
            ps.setString(4, Row);
            ps.setString(5, pay);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Added Successfully!");
        }catch(Exception e){
            //java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnADDreActionPerformed

    private void btnResetreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetreActionPerformed
        // TODO add your handling code here:
        resofidtxt.setText("");
        cnametxt.setText("");
        paytxt.setText("");
        clnametxt.setText("");
    }//GEN-LAST:event_btnResetreActionPerformed

    private void btnDELETEreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEreActionPerformed
        // TODO add your handling code here:

        try{
            updateAddDelResOffers();

            switch(flag){
                case 0:
                ps = sqlConn.prepareStatement("DELETE FROM reservation_offers WHERE reservation_offer_id=?");
                ps.setString(1, resofid);
                ps.executeUpdate();
                case 1:
                ps = sqlConn.prepareStatement("DELETE FROM reservation_offers WHERE reservation_offer_id=? AND (customer_lname LIKE ?)");
                ps.setString(1, resofid);
                ps.setString(2, clname);
                ps.executeUpdate();
                case 2:
                ps = sqlConn.prepareStatement("DELETE FROM reservation_offers WHERE reservation_offer_id=? AND (customer_name LIKE ?)");
                ps.setString(1, resofid);
                ps.setString(2, cname);
                ps.executeUpdate();
                case 3:
                ps = sqlConn.prepareStatement("DELETE FROM reservation_offers WHERE reservation_offer_id=? AND off_id=?");
                ps.setString(1, resofid);
                ps.setString(2, Row);
                ps.executeUpdate();
                case 4:
                ps = sqlConn.prepareStatement("DELETE FROM reservation_offers WHERE reservation_offer_id=? AND payment_in_advance=?");
                ps.setString(1, resofid);
                ps.setString(2, pay);
                ps.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
        }catch(Exception e){
            //java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnDELETEreActionPerformed

    private void clnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clnametxtActionPerformed

    private void cnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnametxtActionPerformed

    private void paytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paytxtActionPerformed

    private void btnResoffersTABLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResoffersTABLEActionPerformed
        // TODO add your handling code here:
        try{
            sqlConn = DriverManager.getConnection(dataB,username,password);
            PreparedStatement pst = sqlConn.prepareStatement("SELECT offer_id FROM offers ORDER BY offer_id");
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new String[]{rs.getString(1)});
            }
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnResoffersTABLEActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        resOffersTable  resofTbl = new resOffersTable();
        resofTbl.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reservationOffersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reservationOffersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reservationOffersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reservationOffersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reservationOffersFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADDre;
    private javax.swing.JButton btnDELETEre;
    private javax.swing.JPanel btnRESETbr;
    private javax.swing.JButton btnResetre;
    private javax.swing.JButton btnResoffersTABLE;
    private javax.swing.JButton btnReturnre;
    private javax.swing.JButton btnUPDATEre;
    private javax.swing.JTextField clnametxt;
    private javax.swing.JTextField cnametxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField paytxt;
    private javax.swing.JTextField resofidtxt;
    // End of variables declaration//GEN-END:variables
}
