
package projectdb_2022_23;

import java.sql.CallableStatement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.table.DefaultTableModel;

public class reservationFrame extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String password = "123456";
    private static final String dataB = "jdbc:mysql://localhost:3306/travel_agency";
    
    Connection sqlConn = null;
    PreparedStatement ps = null;
    
    String tripid = null;
    String seatnum = null;
    String name = null;
    String lname = null;
    String isadult = null;
    int flag;
    
    public reservationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
        public void updateAddDelReservation(){
        try{
             tripid = wretrIDtxt.getText();
             seatnum = renumOstxt.getText();
             name = renametxt.getText();
             lname = relnametxt.getText();
             isadult = readulttxt.getText();
             
             if(!(seatnum.isEmpty()) && name.isEmpty() && lname.isEmpty() && isadult.isEmpty())
                 flag = 1;
             else if(!(name.isEmpty()) && seatnum.isEmpty() && isadult.isEmpty() && lname.isEmpty())
                 flag = 2;
             else if(!(lname.isEmpty()) && name.isEmpty() && seatnum.isEmpty() && isadult.isEmpty())
                 flag = 3;
             else if(!(isadult.isEmpty()) && lname.isEmpty() && name.isEmpty() && !(seatnum.isEmpty()))
                 flag = 4;
             else
                 flag = 0;
             
 
             Class.forName("com.mysql.jdbc.Driver");
             sqlConn = DriverManager.getConnection(dataB,username,password);
        }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, e);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
        
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRESETbr = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnReturnre = new javax.swing.JButton();
        wretrIDtxt = new javax.swing.JTextField();
        btnUPDATEre = new javax.swing.JButton();
        btnADDre = new javax.swing.JButton();
        btnResetre = new javax.swing.JButton();
        btnDELETEre = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        renumOstxt = new javax.swing.JTextField();
        renametxt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        relnametxt = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        readulttxt = new javax.swing.JTextField();
        btnResTABLE = new javax.swing.JButton();
        btnShowRes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRESETbr.setBackground(new java.awt.Color(0, 0, 0));
        btnRESETbr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 8));
        btnRESETbr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Reservation Table");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnRESETbr.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 380, 70));

        btnReturnre.setFont(new java.awt.Font("Segoe UI Semibold", 1, 26)); // NOI18N
        btnReturnre.setText("Return");
        btnReturnre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReturnre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnreActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnReturnre, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 720, 130, 50));

        wretrIDtxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        wretrIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wretrIDtxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(wretrIDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 460, 30));

        btnUPDATEre.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnUPDATEre.setText("UPDATE");
        btnUPDATEre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUPDATEre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEreActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnUPDATEre, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, 130, 50));

        btnADDre.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnADDre.setText("ADD");
        btnADDre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnADDre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDreActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnADDre, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 250, 130, 50));

        btnResetre.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnResetre.setText("RESET");
        btnResetre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetreActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnResetre, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, 130, 50));

        btnDELETEre.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnDELETEre.setText("DELETE");
        btnDELETEre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDELETEre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEreActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnDELETEre, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, 130, 50));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("trip id");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 140, 30));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("number of seats");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnRESETbr.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 190, 30));

        renumOstxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        renumOstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renumOstxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(renumOstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 460, 30));

        renametxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        renametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renametxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(renametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 460, 30));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 0));
        jLabel8.setText("Lastname");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 120, -1));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("Name");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 120, -1));

        relnametxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        relnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relnametxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(relnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 460, 30));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setText("Adult or Minor");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 170, -1));

        readulttxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        readulttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readulttxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(readulttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 460, 30));

        btnResTABLE.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnResTABLE.setText("RESERVATION TABLE");
        btnResTABLE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResTABLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResTABLEActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnResTABLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, 170, 40));

        btnShowRes.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnShowRes.setText("SHOW RESERVATIONS");
        btnShowRes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowResActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnShowRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 620, 170, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "off", "name", "last", "number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnRESETbr.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 690, 170));

        getContentPane().add(btnRESETbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnreActionPerformed
        // TODO add your handling code here:
        IT_operationsFrame s = new IT_operationsFrame();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturnreActionPerformed

    private void wretrIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wretrIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wretrIDtxtActionPerformed

    private void btnUPDATEreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEreActionPerformed
        // TODO add your handling code here:

        try{
            updateAddDelReservation();

            switch(flag){
                case 0:
                ps = sqlConn.prepareStatement("UPDATE reservation set res_name=?,res_lname=?,res_isadult=? WHERE res_tr_id=? AND res_seatnum=?");
                ps.setString(5, seatnum);
                ps.setString(1, name);
                ps.setString(2, lname);
                ps.setString(3, isadult);
                ps.setString(4, tripid);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                case 2:
                    
                ps = sqlConn.prepareStatement("UPDATE reservation set res_name=? WHERE res_tr_id=? AND res_seatnum=?");
                ps.setString(2, tripid);
                ps.setString(1, name);
                ps.setString(3, seatnum);
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                case 3:
                ps = sqlConn.prepareStatement("UPDATE reservation set res_lname=? WHERE res_tr_id=? AND res_seatnum=?");
                ps.setString(2, tripid);
                ps.setString(1, lname);
                ps.setString(3, seatnum);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                case 4:
                ps = sqlConn.prepareStatement("UPDATE reservation set res_isadult=? WHERE res_tr_id=? AND res_seatnum=?");
                ps.setString(2, tripid);
                ps.setString(1, isadult);
                ps.setString(3, seatnum);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
            }

        }catch(Exception e){
            //java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
            System.out.println(e);
        }
    }//GEN-LAST:event_btnUPDATEreActionPerformed

    private void btnADDreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDreActionPerformed
        // TODO add your handling code here:

        try{
            updateAddDelReservation();

            ps = sqlConn.prepareStatement("insert into reservation values(?,?,?,?,?)");

            ps.setString(1, tripid);
            ps.setString(2,seatnum);
            ps.setString(3, name);
            ps.setString(4, lname);
            ps.setString(5, isadult);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Added Successfully!");
        }catch(Exception e){
            //java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnADDreActionPerformed

    private void btnResetreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetreActionPerformed
        // TODO add your handling code here:
        wretrIDtxt.setText("");
        renametxt.setText("");
        relnametxt.setText("");
        renumOstxt.setText("");
    }//GEN-LAST:event_btnResetreActionPerformed

    private void btnDELETEreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEreActionPerformed
        // TODO add your handling code here:

        try{
            updateAddDelReservation();

            switch(flag){
                case 0:
                    ps = sqlConn.prepareStatement("DELETE FROM reservation WHERE res_tr_id=?");
                    ps.setString(1, tripid);
                    ps.executeUpdate();
                case 1:
                    ps = sqlConn.prepareStatement("DELETE FROM reservation WHERE res_tr_id=? AND res_seatnum=?");
                    ps.setString(1, tripid);
                    ps.setString(2, seatnum);
                ps.executeUpdate();
                case 2:
                    ps = sqlConn.prepareStatement("DELETE FROM reservation WHERE res_tr_id=? AND (res_name=?)");
                    ps.setString(1, tripid);
                    ps.setString(2, name);
                    ps.executeUpdate();
                case 3:
                    ps = sqlConn.prepareStatement("DELETE FROM reservation WHERE res_tr_id=? AND (res_lname=?)");
                    ps.setString(1, tripid);
                    ps.setString(2, lname);
                    ps.executeUpdate();
                case 4:
                    ps = sqlConn.prepareStatement("DELETE FROM reservation WHERE res_tr_id=? AND (res_isadult=?)");
                    ps.setString(1, tripid);
                    ps.setString(2, isadult);
                    ps.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
        }catch(Exception e){
            //java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnDELETEreActionPerformed

    private void renumOstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renumOstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_renumOstxtActionPerformed

    private void renametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_renametxtActionPerformed

    private void relnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relnametxtActionPerformed

    private void readulttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readulttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readulttxtActionPerformed

    private void btnResTABLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResTABLEActionPerformed
        // TODO add your handling code here:
        Tablereservation c = new Tablereservation();
        c.setVisible(true);
    }//GEN-LAST:event_btnResTABLEActionPerformed

    private void btnShowResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowResActionPerformed
        // TODO add your handling code here:
        try{
            updateAddDelReservation();
            CallableStatement cs = sqlConn.prepareCall("{call prosfora(?)}");
            cs.setString(1, lname);
            ResultSet rs = cs.executeQuery();
            
            DefaultTableModel model = new DefaultTableModel();
            jTable1.setModel(model);
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();
            
            for (int i = 1; i <= columnCount; i++) {
                model.addColumn(metaData.getColumnLabel(i));
            }
            
            while (rs.next()) {
                Object[] rowData = new Object[columnCount];
                for (int i = 1; i <= columnCount; i++) {
                    rowData[i - 1] = rs.getObject(i);
                }
                model.addRow(rowData);
            }
            cs.close();
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnShowResActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reservationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reservationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reservationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reservationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reservationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADDre;
    private javax.swing.JButton btnDELETEre;
    private javax.swing.JPanel btnRESETbr;
    private javax.swing.JButton btnResTABLE;
    private javax.swing.JButton btnResetre;
    private javax.swing.JButton btnReturnre;
    private javax.swing.JButton btnShowRes;
    private javax.swing.JButton btnUPDATEre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField readulttxt;
    private javax.swing.JTextField relnametxt;
    private javax.swing.JTextField renametxt;
    private javax.swing.JTextField renumOstxt;
    private javax.swing.JTextField wretrIDtxt;
    // End of variables declaration//GEN-END:variables
}
