
package projectdb_2022_23;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;

public class tripFrame extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String password = "123456";
    private static final String dataB = "jdbc:mysql://localhost:3306/travel_agency";
    
    Connection sqlConn = null;
    PreparedStatement ps = null;
    
    String tripID = null;
    String deptime = null;
    String retime = null;
    String maxs = null;
    String cost = null;
    String trbrcode = null;
    String trgui = null;
    String trdrv = null;
    int flag;
    
    public tripFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void updateAddDelTrip(){
        try{
             tripID = tripIdtxt.getText();
             deptime = trDeptimetxt.getText();
             retime = trRettimetxt.getText();
             maxs = trMaxtxt.getText();
             cost = trcosttxt.getText();
             trbrcode = trbrcodetxt.getText();
             trgui = trguiATtxt.getText();
             trdrv = trdrATtxt.getText();
             
             if(!(deptime.isEmpty()) && retime.isEmpty() && maxs.isEmpty() && cost.isEmpty() && trbrcode.isEmpty() && trgui.isEmpty() && trdrv.isEmpty())
                 flag = 1;
             else if(deptime.isEmpty() && !(retime.isEmpty()) && maxs.isEmpty() && cost.isEmpty() && trbrcode.isEmpty() && trgui.isEmpty() && trdrv.isEmpty())
                 flag = 2;
             else if(deptime.isEmpty() && retime.isEmpty() && !(maxs.isEmpty()) && cost.isEmpty() && trbrcode.isEmpty() && trgui.isEmpty() && trdrv.isEmpty())
                 flag = 3;
             else if(deptime.isEmpty() && retime.isEmpty() && maxs.isEmpty() && !(cost.isEmpty()) && trbrcode.isEmpty() && trgui.isEmpty() && trdrv.isEmpty())
                 flag = 4;
             else if(deptime.isEmpty() && retime.isEmpty() && maxs.isEmpty() && cost.isEmpty() && !(trbrcode.isEmpty()) && trgui.isEmpty() && trdrv.isEmpty())
                 flag = 5;
             else if(deptime.isEmpty() && retime.isEmpty() && maxs.isEmpty() && cost.isEmpty() && trbrcode.isEmpty() && !(trgui.isEmpty()) && trdrv.isEmpty())
                 flag = 6;
             else if(deptime.isEmpty() && retime.isEmpty() && maxs.isEmpty() && cost.isEmpty() && trbrcode.isEmpty() && trgui.isEmpty() && !(trdrv.isEmpty()))
                 flag = 7;
             else
                 flag = 0;
 
             Class.forName("com.mysql.jdbc.Driver");
             sqlConn = DriverManager.getConnection(dataB,username,password);
        }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, e);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRESETbr = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnReturnbr = new javax.swing.JButton();
        tripIdtxt = new javax.swing.JTextField();
        btnUPDATEtr = new javax.swing.JButton();
        btnADDtr = new javax.swing.JButton();
        btnResettr = new javax.swing.JButton();
        btnDELETEtr = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        trDeptimetxt = new javax.swing.JTextField();
        trRettimetxt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        trMaxtxt = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        trcosttxt = new javax.swing.JTextField();
        btnTripTABLE = new javax.swing.JButton();
        trguiATtxt = new javax.swing.JTextField();
        trbrcodetxt = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        trdrATtxt = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnAvtrips = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRESETbr.setBackground(new java.awt.Color(0, 0, 0));
        btnRESETbr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 8));
        btnRESETbr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Trip Table");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 380, 70));

        btnReturnbr.setFont(new java.awt.Font("Segoe UI Semibold", 1, 26)); // NOI18N
        btnReturnbr.setText("Return");
        btnReturnbr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReturnbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnbrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnReturnbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 700, 130, 50));

        tripIdtxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        tripIdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tripIdtxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(tripIdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 460, 30));

        btnUPDATEtr.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnUPDATEtr.setText("UPDATE");
        btnUPDATEtr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUPDATEtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEtrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnUPDATEtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, 130, 50));

        btnADDtr.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnADDtr.setText("ADD");
        btnADDtr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnADDtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDtrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnADDtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, 130, 50));

        btnResettr.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnResettr.setText("RESET");
        btnResettr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResettr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResettrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnResettr, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, 130, 50));

        btnDELETEtr.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnDELETEtr.setText("DELETE");
        btnDELETEtr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDELETEtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEtrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnDELETEtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 340, 130, 50));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("trip id");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 140, 30));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("departure time");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, 30));

        trDeptimetxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        trDeptimetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trDeptimetxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(trDeptimetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 460, 30));

        trRettimetxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        trRettimetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trRettimetxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(trRettimetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 460, 30));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 0));
        jLabel8.setText("maximum seats");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 190, -1));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("return time");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 180, -1));

        trMaxtxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        trMaxtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trMaxtxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(trMaxtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 460, 30));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setText("cost");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 120, -1));

        trcosttxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        trcosttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trcosttxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(trcosttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 460, 30));

        btnTripTABLE.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        btnTripTABLE.setText("TRIP TABLE");
        btnTripTABLE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTripTABLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTripTABLEActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnTripTABLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 130, 40));

        trguiATtxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        trguiATtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trguiATtxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(trguiATtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 460, -1));

        trbrcodetxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        trbrcodetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trbrcodetxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(trbrcodetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 460, 30));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 0));
        jLabel10.setText("guide AT");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 0));
        jLabel11.setText("driver AT");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 170, -1));

        trdrATtxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        trdrATtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trdrATtxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(trdrATtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, 460, -1));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 0));
        jLabel9.setText("branch code");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 170, -1));

        btnAvtrips.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnAvtrips.setText("AVAILABLE TRIPS");
        btnAvtrips.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAvtrips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvtripsActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnAvtrips, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 580, 130, 40));

        getContentPane().add(btnRESETbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnbrActionPerformed
        // TODO add your handling code here:
        IT_operationsFrame s = new IT_operationsFrame();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturnbrActionPerformed

    private void tripIdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripIdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tripIdtxtActionPerformed

    private void btnUPDATEtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEtrActionPerformed
        // TODO add your handling code here:

        try{
            updateAddDelTrip();

            switch(flag){
                case 0:
                    ps = sqlConn.prepareStatement("UPDATE trip set tr_departure=?,tr_return=?,tr_maxseats=?,tr_cost=?,tr_br_code=?,tr_gui_AT=?,tr_drv_AT=? WHERE tr_id=?");
                    ps.setString(1, deptime);
                    ps.setString(2, retime);
                    ps.setString(3, maxs);
                    ps.setString(4, cost);
                    ps.setString(5, trbrcode);
                    ps.setString(6, trgui);
                    ps.setString(7, trdrv);
                    ps.setString(8, tripID);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                case 1:
                    ps = sqlConn.prepareStatement("UPDATE trip set tr_departure=? WHERE tr_id=?");
                    ps.setString(2, tripID);
                    ps.setString(1, deptime);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                case 2:
                    ps = sqlConn.prepareStatement("UPDATE trip set tr_return=? WHERE tr_id=?");
                    ps.setString(2, tripID);
                    ps.setString(1, retime);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                case 3:
                    ps = sqlConn.prepareStatement("UPDATE trip set tr_maxseats=? WHERE tr_id=?");
                    ps.setString(2, tripID);
                    ps.setString(1, maxs);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                case 4:
                    ps = sqlConn.prepareStatement("UPDATE trip set tr_cost=? WHERE tr_id=?");
                    ps.setString(2, tripID);
                    ps.setString(1, cost);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                case 5:
                    ps = sqlConn.prepareStatement("UPDATE trip set tr_br_code=? WHERE tr_id=?");
                    ps.setString(2, tripID);
                    ps.setString(1, trbrcode);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                case 6:
                    ps = sqlConn.prepareStatement("UPDATE trip set tr_gui_AT=? WHERE tr_id=?");
                    ps.setString(2, tripID);
                    ps.setString(1, trgui);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                case 7:
                    ps = sqlConn.prepareStatement("UPDATE trip set tr_drv_AT=? WHERE tr_id=?");
                    ps.setString(2, tripID);
                    ps.setString(1, trdrv);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
            }

        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnUPDATEtrActionPerformed

    private void btnADDtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDtrActionPerformed
        // TODO add your handling code here:

        try{
            updateAddDelTrip();

            ps = sqlConn.prepareStatement("insert into trip(tr_id,tr_departure,tr_return,tr_maxseats,tr_cost,tr_br_code,tr_gui_AT,tr_drv_AT)values(?,?,?,?,?,?,?,?)");

            ps.setString(1, tripID);
            ps.setString(2,deptime);
            ps.setString(3, retime);
            ps.setString(4, maxs);
            ps.setString(5, cost);
            ps.setString(6, trbrcode);
            ps.setString(7, trgui);
            ps.setString(8, trdrv);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Added Successfully!");
        }catch(Exception e){
            //java.util.logging.Logger.getLogger(branchFrame.class.getName()).log(java.util.logging.Level.SEVERE,null,e);
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnADDtrActionPerformed

    private void btnResettrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResettrActionPerformed
        // TODO add your handling code here:
        tripIdtxt.setText("");
        trRettimetxt.setText("");
        trMaxtxt.setText("");
        trDeptimetxt.setText("");
        trcosttxt.setText("");
        trbrcodetxt.setText("");
        trguiATtxt.setText("");
        trdrATtxt.setText("");
    }//GEN-LAST:event_btnResettrActionPerformed

    private void btnDELETEtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEtrActionPerformed
        // TODO add your handling code here:

        try{
            updateAddDelTrip();

            switch(flag){
                case 0:
                    ps = sqlConn.prepareStatement("DELETE FROM trip WHERE tr_id=?");
                    ps.setString(1, tripID);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
                case 1:
                    ps = sqlConn.prepareStatement("DELETE FROM trip WHERE (tr_id=? AND tr_departure=?)");
                    ps.setString(1, tripID);
                    ps.setString(2, deptime);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
                case 2:
                    ps = sqlConn.prepareStatement("DELETE FROM trip WHERE (tr_id=? AND tr_return=?)");
                    ps.setString(1, tripID);
                    ps.setString(2, retime);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
                case 3:
                    ps = sqlConn.prepareStatement("DELETE FROM trip WHERE (tr_id=? AND tr_maxseats=?)");
                    ps.setString(1, tripID);
                    ps.setString(2, maxs);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
                case 4:
                    ps = sqlConn.prepareStatement("DELETE FROM trip WHERE (tr_id=? AND tr_cost=?)");
                    ps.setString(1, tripID);
                    ps.setString(2, cost);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
                case 5:
                    ps = sqlConn.prepareStatement("DELETE FROM trip WHERE (tr_id=? AND tr_br_code=?)");
                    ps.setString(1, tripID);
                    ps.setString(2, trbrcode);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
                case 6:
                    ps = sqlConn.prepareStatement("DELETE FROM trip WHERE (tr_id=? AND tr_gui_AT=?)");
                    ps.setString(1, tripID);
                    ps.setString(2, trgui);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
                case 7:
                    ps = sqlConn.prepareStatement("DELETE FROM trip WHERE (tr_id=? AND tr_drv_AT=?)");
                    ps.setString(1, tripID);
                    ps.setString(2, trdrv);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnDELETEtrActionPerformed

    private void trDeptimetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trDeptimetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trDeptimetxtActionPerformed

    private void trRettimetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trRettimetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trRettimetxtActionPerformed

    private void trMaxtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trMaxtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trMaxtxtActionPerformed

    private void trcosttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trcosttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trcosttxtActionPerformed

    private void btnTripTABLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTripTABLEActionPerformed
        // TODO add your handling code here:
        Tabletrip Ttr = new Tabletrip();
        Ttr.setVisible(true);
    }//GEN-LAST:event_btnTripTABLEActionPerformed

    private void trbrcodetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trbrcodetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trbrcodetxtActionPerformed

    private void trguiATtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trguiATtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trguiATtxtActionPerformed

    private void trdrATtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trdrATtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trdrATtxtActionPerformed

    private void btnAvtripsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvtripsActionPerformed
        // TODO add your handling code here:
        tripProcedure pr = new tripProcedure();
        pr.setVisible(true);
    }//GEN-LAST:event_btnAvtripsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tripFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tripFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tripFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tripFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tripFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADDtr;
    private javax.swing.JButton btnAvtrips;
    private javax.swing.JButton btnDELETEtr;
    private javax.swing.JPanel btnRESETbr;
    private javax.swing.JButton btnResettr;
    private javax.swing.JButton btnReturnbr;
    private javax.swing.JButton btnTripTABLE;
    private javax.swing.JButton btnUPDATEtr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField trDeptimetxt;
    private javax.swing.JTextField trMaxtxt;
    private javax.swing.JTextField trRettimetxt;
    private javax.swing.JTextField trbrcodetxt;
    private javax.swing.JTextField trcosttxt;
    private javax.swing.JTextField trdrATtxt;
    private javax.swing.JTextField trguiATtxt;
    private javax.swing.JTextField tripIdtxt;
    // End of variables declaration//GEN-END:variables
}
