
package projectdb_2022_23;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;

public class workerFrame extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String password = "123456";
    private static final String dataB = "jdbc:mysql://localhost:3306/travel_agency";
    
    Connection sqlConn = null;
    PreparedStatement ps = null;
    
    String workerAT = null;
    String wrkname = null;
    String wrklname = null;
    String wrksalary = null;
    String wrkbrcode = null;
    int flag;
    
    public workerFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void updateAddDelWorker(){
        try{
             workerAT = wrkATtxt.getText();
             wrkname = wrknametxt.getText();
             wrklname = wrklnametxt.getText();
             wrksalary = wrksalarytxt.getText();
             wrkbrcode = wrkbrcodetxt.getText();
             
             if(!(wrkname.isEmpty()) && wrklname.isEmpty() && wrksalary.isEmpty() && wrkbrcode.isEmpty())
                 flag = 1;
             else if(!(wrklname.isEmpty()) && wrkname.isEmpty() && wrksalary.isEmpty() && wrkbrcode.isEmpty())
                 flag = 2;
             else if(!(wrksalary.isEmpty()) && wrklname.isEmpty() && wrkname.isEmpty() && wrkbrcode.isEmpty())
                 flag = 3;
             else if(!(wrkbrcode.isEmpty()) && wrklname.isEmpty() && wrkname.isEmpty() && wrksalary.isEmpty())
                 flag = 4;
             else
                 flag = 0;
 
             Class.forName("com.mysql.jdbc.Driver");
             sqlConn = DriverManager.getConnection(dataB,username,password);
        }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, e);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnRESETbr = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnReturnbr = new javax.swing.JButton();
        wrkATtxt = new javax.swing.JTextField();
        btnUPDATEbr = new javax.swing.JButton();
        btnADDbr = new javax.swing.JButton();
        btnResetbr = new javax.swing.JButton();
        btnDELETEbr = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        wrknametxt = new javax.swing.JTextField();
        wrklnametxt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        wrksalarytxt = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        wrkbrcodetxt = new javax.swing.JTextField();
        btnWorkerTABLE = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("city");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRESETbr.setBackground(new java.awt.Color(0, 0, 0));
        btnRESETbr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 8));
        btnRESETbr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Worker Table");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 380, 70));

        btnReturnbr.setFont(new java.awt.Font("Segoe UI Semibold", 1, 26)); // NOI18N
        btnReturnbr.setText("Return");
        btnReturnbr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReturnbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnbrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnReturnbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, 130, 50));

        wrkATtxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        wrkATtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrkATtxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(wrkATtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 460, 30));

        btnUPDATEbr.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnUPDATEbr.setText("UPDATE");
        btnUPDATEbr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUPDATEbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPDATEbrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnUPDATEbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, 130, 50));

        btnADDbr.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnADDbr.setText("ADD");
        btnADDbr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnADDbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDbrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnADDbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 250, 130, 50));

        btnResetbr.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnResetbr.setText("RESET");
        btnResetbr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetbrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnResetbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, 130, 50));

        btnDELETEbr.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnDELETEbr.setText("DELETE");
        btnDELETEbr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDELETEbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEbrActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnDELETEbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, 130, 50));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("worker AT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 140, 30));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("Name");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 150, 30));

        wrknametxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        wrknametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrknametxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(wrknametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 460, 30));

        wrklnametxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        wrklnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrklnametxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(wrklnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 460, 30));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 0));
        jLabel8.setText("Salary");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("Lastname");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnRESETbr.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        wrksalarytxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        wrksalarytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrksalarytxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(wrksalarytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 460, 30));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setText("branch code");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRESETbr.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        wrkbrcodetxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        wrkbrcodetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrkbrcodetxtActionPerformed(evt);
            }
        });
        btnRESETbr.add(wrkbrcodetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 460, 30));

        btnWorkerTABLE.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnWorkerTABLE.setText("WORKER TABLE");
        btnWorkerTABLE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWorkerTABLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkerTABLEActionPerformed(evt);
            }
        });
        btnRESETbr.add(btnWorkerTABLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, 130, 40));

        getContentPane().add(btnRESETbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnbrActionPerformed
        // TODO add your handling code here:
        IT_operationsFrame s = new IT_operationsFrame();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturnbrActionPerformed

    private void wrkATtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrkATtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wrkATtxtActionPerformed

    private void btnUPDATEbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPDATEbrActionPerformed
        // TODO add your handling code here:
        try{
            updateAddDelWorker();
            
            switch(flag){
                    case 0:
                            ps = sqlConn.prepareStatement("UPDATE worker set wrk_name=?,wrk_lname=?,wrk_salary=?,wrk_br_code=? WHERE wrk_AT=?");
                            ps.setString(1, wrkname);
                            ps.setString(2, wrklname);
                            ps.setString(3, wrksalary);
                            ps.setString(4, wrkbrcode);
                            ps.setString(5, workerAT);
                            ps.executeUpdate();
                            JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                    case 1:
                            ps = sqlConn.prepareStatement("UPDATE worker set wrk_name=? WHERE wrk_AT=?");
                            ps.setString(2, workerAT);
                            ps.setString(1, wrkname);
                            ps.executeUpdate();
                    case 2:
                            ps = sqlConn.prepareStatement("UPDATE worker set wrk_lname=? WHERE wrk_AT=?");
                            ps.setString(2, workerAT);
                            ps.setString(1, wrklname);
                            ps.executeUpdate();
                            JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                    case 3:
                            ps = sqlConn.prepareStatement("UPDATE worker set wrk_salary=? WHERE wrk_AT=?");
                            ps.setString(2, workerAT);
                            ps.setString(1, wrksalary);
                            ps.executeUpdate();
                            JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
                    case 4:
                            ps = sqlConn.prepareStatement("UPDATE worker set wrk_br_code=? WHERE wrk_AT=?");
                            ps.setString(2, workerAT);
                            ps.setString(1, wrkbrcode);
                            ps.executeUpdate();
                            JOptionPane.showMessageDialog(this, "Record Updated Successfully!");
            }
        }catch(java.sql.SQLException e){
            System.out.println(e);
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnUPDATEbrActionPerformed

    private void btnADDbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDbrActionPerformed
        // TODO add your handling code here:

        try{
            updateAddDelWorker();

            ps = sqlConn.prepareStatement("insert into worker(wrk_AT,wrk_name,wrk_lname,wrk_salary,wrk_br_code)values(?,?,?,?,?)");

            ps.setString(1, workerAT);
            ps.setString(2,wrkname);
            ps.setString(3, wrklname);
            ps.setString(4, wrksalary);
            ps.setString(5, wrkbrcode);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Added Successfully!");
        }catch(java.sql.SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnADDbrActionPerformed

    private void btnResetbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetbrActionPerformed
        // TODO add your handling code here:
        wrkATtxt.setText("");
        wrklnametxt.setText("");
        wrksalarytxt.setText("");
        wrknametxt.setText("");
        wrkbrcodetxt.setText("");
    }//GEN-LAST:event_btnResetbrActionPerformed

    private void btnDELETEbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEbrActionPerformed
        // TODO add your handling code here:
        try{
            updateAddDelWorker();
            if(!(wrklname.isEmpty()) && !(wrkname.isEmpty()) && wrkbrcode.isEmpty() && wrksalary.isEmpty()){
                    ps = sqlConn.prepareStatement("DELETE FROM worker WHERE (wrk_name LIKE ? AND wrk_lname LIKE ?)");
                    ps.setString(1, wrkname);
                    ps.setString(2, wrklname);
                    ps.execute();
                    JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
            }else{
            
            switch(flag){
                case 0:
                        ps = sqlConn.prepareStatement("DELETE FROM worker WHERE wrk_AT=?");
                        ps.setString(1, workerAT);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
                case 1:
                        ps = sqlConn.prepareStatement("DELETE FROM worker WHERE wrk_AT=? AND (wrk_name=?)");
                        ps.setString(1, workerAT);
                        ps.setString(2, wrkname);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
                case 2:
                        ps = sqlConn.prepareStatement("DELETE FROM worker WHERE wrk_AT=? AND (wrk_lname=?)");
                        ps.setString(1, workerAT);
                        ps.setString(2, wrklname);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
                case 3:
                        ps = sqlConn.prepareStatement("DELETE FROM worker WHERE wrk_AT=? AND wrk_salary=?");
                        ps.setString(1, workerAT);
                        ps.setString(2, wrksalary);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
                case 4:
                        ps = sqlConn.prepareStatement("DELETE FROM worker WHERE wrk_AT=? AND wrk_br_code=?");
                        ps.setString(1, workerAT);
                        ps.setString(2, wrkbrcode);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Record Deleted Successfully!");
            }
            }
        }catch(java.sql.SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }catch(Exception e){
            System.out.print(e);
        }

    }//GEN-LAST:event_btnDELETEbrActionPerformed

    private void wrknametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrknametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wrknametxtActionPerformed

    private void wrklnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrklnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wrklnametxtActionPerformed

    private void wrksalarytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrksalarytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wrksalarytxtActionPerformed

    private void wrkbrcodetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrkbrcodetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wrkbrcodetxtActionPerformed

    private void btnWorkerTABLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkerTABLEActionPerformed
        // TODO add your handling code here:
        Tableworker c = new Tableworker();
        c.setVisible(true);
    }//GEN-LAST:event_btnWorkerTABLEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(workerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(workerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(workerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(workerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new workerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADDbr;
    private javax.swing.JButton btnDELETEbr;
    private javax.swing.JPanel btnRESETbr;
    private javax.swing.JButton btnResetbr;
    private javax.swing.JButton btnReturnbr;
    private javax.swing.JButton btnUPDATEbr;
    private javax.swing.JButton btnWorkerTABLE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField wrkATtxt;
    private javax.swing.JTextField wrkbrcodetxt;
    private javax.swing.JTextField wrklnametxt;
    private javax.swing.JTextField wrknametxt;
    private javax.swing.JTextField wrksalarytxt;
    // End of variables declaration//GEN-END:variables
}
